language: node_js
node_js:
  - "10"

env:
  - CXX=clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - g++-4.8
      - llvm-3.6
      - libstdc++-4.9-dev
      - llvm-3.6-dev
      - clang-3.6

compiler: clang

sudo: false

os:
  - linux
  - osx

osx_image: xcode7.2

before_install:
  - export TSD_GITHUB_TOKEN=8591f447276e1caa1b9636b9c8053d768130464f
  - gcc --version

script:
  - npm run build:source
  - npm run coverage

after_success:
  - npm run coveralls

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules
